=== hcts-hra/ecpo/data/annotator_data/Jingbao/generated-schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "items": {"$ref": "#/definitions/items_type"},
        "partOf": {"$ref": "#/definitions/partOf_type"},
        "@context": {"type": "string"},
        "startIndex": {"type": "integer"},
        "next": {"type": "string"},
        "last": {"type": "string"},
        "type": {"type": "string"},
        "id": {"type": "string"}
    },
    "definitions": {
        "value_type": {
            "type": "object",
            "properties": {
                "color": {"type": "string"},
                "name": {"type": "string"},
                "label": {"type": "string"}
            }
        },
        "body_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "value": {"$ref": "#/definitions/value_type"},
                    "type": {"type": "string"}
                },
                "required": [
                    "type",
                    "value"
                ]
            }
        },
        "selector_type": {
            "type": "object",
            "properties": {
                "value": {"type": "string"},
                "type": {"type": "string"}
            }
        },
        "target_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "type": {"type": "string"},
                    "source": {"type": "string"},
                    "id": {"type": "string"},
                    "selector": {"$ref": "#/definitions/selector_type"}
                },
                "required": [
                    "selector",
                    "source",
                    "id",
                    "type"
                ]
            }
        },
        "items_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "body": {"$ref": "#/definitions/body_type"},
                    "created": {"type": "string"},
                    "target": {"$ref": "#/definitions/target_type"},
                    "type": {"type": "string"},
                    "id": {"type": "string"}
                },
                "required": [
                    "created",
                    "id",
                    "body",
                    "type",
                    "target"
                ]
            }
        },
        "partOf_type": {
            "type": "object",
            "properties": {
                "total": {"type": "integer"},
                "modified": {"type": "string"},
                "id": {"type": "string"}
            }
        }
    }
}

=== hcts-hra/ecpo/data/annotator_data/Jingbao/1939/04/jb_3804_1939-04-30_0002+0003.json
{"items":[{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:11:58.104Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614791180989","selector":{"value":"<g transform=\"matrix(1 0 0 1 1109.71712 1239.11808)\"><polygon points=\"-75.52416,47.78848 75.52416,46.67712 75.52416,-47.78848 -75.57248,-46.67712 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561479118104"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:28:39.760Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614801197574","selector":{"value":"<g transform=\"matrix(1 0 0 1 3946.7776 2778.97984)\"><polygon points=\"-19.42464,-339.78624 19.42464,-339.78624 19.42464,339.78624 -19.42464,339.78624 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561480119760"},{"body":[{"value":{"color":"blue","name":"image","label":"Image or Drawing"},"type":"CategoryLabel"}],"created":"2019-06-25T16:28:30.990Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614801109868","selector":{"value":"<g transform=\"matrix(1 0 0 1 3770.46 2349.9)\" id=\"s-15614801109868\">\n<polygon points=\"-190.82,-42.38 190.82,-42.38 190.82,42.38 -190.82,42.38 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561480110990"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2022-06-23T23:01:40.120Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-16560253001183","selector":{"value":"<g transform=\"matrix(1 0 0 1 3193.41 2368.44)\" id=\"s-16560253001183\">\n<polygon points=\"-37.99,-40.13 37.99,-40.13 37.99,40.13 -37.99,40.13 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1656025300120"},{"body":[{"value":{"color":"blue","name":"image","label":"Image or Drawing"},"type":"CategoryLabel"}],"created":"2022-06-23T23:01:42.736Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-16560253027346","selector":{"value":"<g transform=\"matrix(1 0 0 1 3189.13 2627.92)\" id=\"s-16560253027346\">\n<polygon points=\"-55.11,-176.55 55.11,-176.55 55.11,176.55 -55.11,176.55 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1656025302736"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2022-06-23T23:01:45.329Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-16560253053276","selector":{"value":"<g transform=\"matrix(1 0 0 1 3188.6 2894.89)\" id=\"s-16560253053276\">\n<polygon points=\"-17.12,-76.5 17.12,-76.5 17.12,76.51 -17.12,76.51 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1656025305329"},{"body":[{"value":{"color":"blue","name":"image","label":"Image or Drawing"},"type":"CategoryLabel"}],"created":"2022-06-23T23:01:48.949Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-16560253089473","selector":{"value":"<g transform=\"matrix(1 0 0 1 3191.81 3035.05)\" id=\"s-16560253089473\">\n<polygon points=\"-34.24,-57.24 34.24,-57.24 34.24,57.24 -34.24,57.24 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1656025308949"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:15:33.053Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-156147933305110","selector":{"value":"<g transform=\"matrix(1 0 0 1 827.86656 2093.31904)\"><polygon points=\"-108.72,156.84672 106.5456,157.95808 109.83136,-156.89504 -109.83136,-157.95808 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561479333053"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:16:00.363Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614793603612","selector":{"value":"<g transform=\"matrix(1 0 0 1 418.58 2093.09)\" id=\"s-15614793603612\">\n<polygon points=\"-61.12,157.94 60.02,157.94 61.11,-157.94 -59.96,-156.95 \"/>\n</g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561479360363"},{"body":[{"value":{"color":"purple","name":"additional","label":"Additional Information"},"type":"CategoryLabel"}],"created":"2019-07-11T20:34:57.151Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15628772971385","selector":{"value":"<g transform=\"matrix(1 0 0 1 2679.63392 452.2752)\"><polygon points=\"-63.83072,-24.98144 63.83072,-24.98144 63.83072,24.98144 -63.83072,24.98144 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1562877297151"},{"body":[{"value":{"color":"purple","name":"additional","label":"Additional Information"},"type":"CategoryLabel"}],"created":"2019-07-11T20:34:51.306Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15628772912967","selector":{"value":"<g transform=\"matrix(1 0 0 1 2983.61504 458.21856)\"><polygon points=\"-66.44,-25.65792 66.44,-25.65792 66.44,25.65792 -66.44,25.65792 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1562877291306"},{"body":[{"value":{"color":"purple","name":"additional","label":"Additional Information"},"type":"CategoryLabel"}],"created":"2019-07-11T20:34:38.419Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15628772784080","selector":{"value":"<g transform=\"matrix(1 0 0 1 3337.60736 472.66624)\"><polygon points=\"-113.84192,-49.33472 113.84192,-49.33472 113.84192,49.33472 -113.84192,49.33472 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1562877278419"},{"body":[{"value":{"color":"purple","name":"additional","label":"Additional Information"},"type":"CategoryLabel"}],"created":"2019-07-11T20:34:32.373Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15628772723612","selector":{"value":"<g transform=\"matrix(1 0 0 1 3883.09184 469.38048)\"><polygon points=\"-251.36064,-30.24832 251.36064,-30.24832 251.36064,30.24832 -251.36064,30.24832 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1562877272373"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:25:54.818Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614799548140","selector":{"value":"<g transform=\"matrix(1 0 0 1 2780.23616 1727.29504)\"><polygon points=\"-226.04096,99.44256 226.04096,105.86912 226.04096,-103.74304 -226.04096,-105.86912 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561479954818"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:25:47.952Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-15614799479504","selector":{"value":"<g transform=\"matrix(1 0 0 1 3064.01952 1730.91904)\"><polygon points=\"-58.90208,106.01408 58.90208,106.01408 58.90208,-106.01408 -58.90208,-106.01408 \"/></g>","type":"SvgSelector"}}],"type":"Annotation","id":"s-1561479947952"},{"body":[{"value":{"color":"orange","name":"article","label":"Article"},"type":"CategoryLabel"}],"created":"2019-06-25T16:25:40.636Z","target":[{"type":"SpecificResource","source":"https://kjc-sv002.kjc.uni-heidelberg.de:8080/fcgi-bin/iipsrv.fcgi?IIIF=imageStorage/ecpo_new/jingbao/1939/04/jb_3804_1939-04-30_0002%252B0003.tif/full/full/0/default.jpg","id":"s-156147994063210","selector":{"value":"<g transform=\"matrix(1 0 0 1 3296.45 1734.55)\" id=\"s-156147994063210\">\n<polygon points=\"-158.65,98.85 154.38,103.11 158.64,-100.98 -157
